---
- name: This is a hello-world example
  hosts: test-servers
  tasks:
    - name: Create a file called '/tmp/testfile1.txt' with the content 'hello wo>
      copy:
        content: Hellooo World...Hi all!!
        dest: /tmp/testfile1.txt
