pipeline {
	agent any
	
	stages {
		stage ('Compile Stage') {
		
			steps {
				sh '''
			cd demoStudent
			mvn clean install
		'''
			}
		}
	}
	post {
		always {
			junit 'demoStudent/target/surefire-reports/*.xml'
			
			}
		}
}
