pipeline {
	agent any
	
	stages {
		stage ('Compile Stage') {
		
			steps {
				sh 'mvn install'
			}
		}
		stage ('Test Stage') {
			steps {
				sh 'mvn test'
				junit 'demoStudent/target/surefire-reports/*.xml'
			}
		}
		stage ('SonarQube Stage') {
			steps {
				withSonarQubeEnv('Sonarqube') {
					sh 'mvn clean install sonar:sonar'
				}			
			}
		}
		
	}
}