pipeline {
	agent any
	
	stages {
		stage ('Compile Stage') {
		
			steps {
				sh '''
			cd demoStudent
			mvn clean install
		'''
			}
		}
		stage ('test') {
			steps {
				junit 'demoStudent/target/surefire-reports/*.xml'
			}	
		}
		stage ('Sonarqube') {
			steps {
				withSonarQubeEnv('SonarQube')	{
					sh 'mvn clean install sonar:sonar'
				}
			}
		}
	}
}